comet_api_key: 'your_comet_api_key'
comet_workspace: 'your comet username'
default_val_root: '/work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/vggface2/val'
default_train_root: '/work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/vggface2/train'
default_test_root: '/work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/vggface2/test'
project_name: frnas
checkpoints_root: Checkpoints/
metadata_file: CelebA/timm_model_metadata.csv
demographics_file: /work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/vggface2/vggface2_demographics.txt