python src/fairness_test_timm.py --config_path configs_multi/tnt_s_patch16_224/config_tnt_s_patch16_224_ArcFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/resnetrs101/config_resnetrs101_CosFace_SGD_0.1_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/resnetrs101/config_resnetrs101_ArcFace_SGD_0.1_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/resnetrs101/config_resnetrs101_MagFace_SGD_0.1_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/tf_efficientnet_b7_ns/config_tf_efficientnet_b7_ns_ArcFace_AdamW_0.001_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/jx_nest_base/config_jx_nest_base_MagFace_AdamW_0.001_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/twins_svt_large/config_twins_svt_large_MagFace_SGD_0.1_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/twins_svt_large/config_twins_svt_large_MagFace_AdamW_0.001_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/twins_svt_large/config_twins_svt_large_ArcFace_AdamW_0.001_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/twins_svt_large/config_twins_svt_large_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_test_timm.py --config_path configs_unified_lr/twins_svt_large/config_twins_svt_large_ArcFace_SGD_0.1_cosine.yaml

