comet_api_key: D1J58R7hYXPZzqZhrTIOe6GGQ
comet_workspace: samueld
default_test_root: /cmlscratch/sdooley1/data/CelebA/Img/img_align_celeba_splits/test/
default_train_root: /cmlscratch/sdooley1/data/CelebA/Img/img_align_celeba_splits/train/
project_name: Phase1B
checkpoints_root: Checkpoints/Phase1B/
metadata_file: /cmlscratch/sdooley1/timm_model_metadata.csv
demographics_file: /cmlscratch/sdooley1/data/CelebA/CelebA_demographics.txt
