comet_api_key: 'your_comet_api_key'
comet_workspace: 'your comet username'
default_val_root: '/work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/VGGFACE2_Cleandata/test'
default_train_root: '/work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/VGGFACE2_Cleandata/train'
default_test_root: '/work/dlclarge2/sukthank-ZCP_Competition/FR-NAS/data/VGGFACE2_Cleandata/test'
project_name: frnas
checkpoints_root: Checkpoints/
metadata_file: CelebA/timm_model_metadata.csv
demographics_file: CelebA/CelebA_demographics.txt