#python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_AdamW_0.001_cosine.yaml
#python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/dpn107/config_dpn107_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/dpn107/config_dpn107_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/dpn107/config_dpn107_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/dpn107/config_dpn107_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/rexnet_200/config_rexnet_200_CosFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/rexnet_200/config_rexnet_200_CosFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/rexnet_200/config_rexnet_200_CosFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/rexnet_200/config_rexnet_200_CosFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/swin_base_patch4_window7_224/config_swin_base_patch4_window7_224_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/swin_base_patch4_window7_224/config_swin_base_patch4_window7_224_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/swin_base_patch4_window7_224/config_swin_base_patch4_window7_224_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/swin_base_patch4_window7_224/config_swin_base_patch4_window7_224_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/coat_lite_small/config_coat_lite_small_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/coat_lite_small/config_coat_lite_small_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/coat_lite_small/config_coat_lite_small_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/coat_lite_small/config_coat_lite_small_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tnt_s_patch16_224/config_tnt_s_patch16_224_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tnt_s_patch16_224/config_tnt_s_patch16_224_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tnt_s_patch16_224/config_tnt_s_patch16_224_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tnt_s_patch16_224/config_tnt_s_patch16_224_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_ArcFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_ArcFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_ArcFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_ArcFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/jx_nest_base/config_jx_nest_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/jx_nest_base/config_jx_nest_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/jx_nest_base/config_jx_nest_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/jx_nest_base/config_jx_nest_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/twins_svt_large/config_twins_svt_large_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/twins_svt_large/config_twins_svt_large_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/twins_svt_large/config_twins_svt_large_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/twins_svt_large/config_twins_svt_large_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/coat_lite_small/config_coat_lite_small_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/coat_lite_small/config_coat_lite_small_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/coat_lite_small/config_coat_lite_small_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/coat_lite_small/config_coat_lite_small_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/twins_svt_large/config_twins_svt_large_CosFace_adamw.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/twins_svt_large/config_twins_svt_large_CosFace_adamw.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/twins_svt_large/config_twins_svt_large_CosFace_adamw.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/twins_svt_large/config_twins_svt_large_CosFace_adamw.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/convit_base/config_convit_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/convit_base/config_convit_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/convit_base/config_convit_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/convit_base/config_convit_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/jx_nest_base/config_jx_nest_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/jx_nest_base/config_jx_nest_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/jx_nest_base/config_jx_nest_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/jx_nest_base/config_jx_nest_base_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/dpn107/config_dpn107_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/twins_svt_large/config_twins_svt_large_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/twins_svt_large/config_twins_svt_large_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/twins_svt_large/config_twins_svt_large_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/twins_svt_large/config_twins_svt_large_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/convit_base/config_convit_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/convit_base/config_convit_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/convit_base/config_convit_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/convit_base/config_convit_base_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/cspdarknet53/config_cspdarknet53_CosFace_adam.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/cspdarknet53/config_cspdarknet53_CosFace_adam.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/cspdarknet53/config_cspdarknet53_CosFace_adam.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/cspdarknet53/config_cspdarknet53_CosFace_adam.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dla102x2/config_dla102x2_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dla102x2/config_dla102x2_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dla102x2/config_dla102x2_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dla102x2/config_dla102x2_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/hrnet_w64/config_hrnet_w64_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/hrnet_w64/config_hrnet_w64_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/hrnet_w64/config_hrnet_w64_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs/hrnet_w64/config_hrnet_w64_CosFace_sgd.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tf_efficientnet_b7_ns/config_tf_efficientnet_b7_ns_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tf_efficientnet_b7_ns/config_tf_efficientnet_b7_ns_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tf_efficientnet_b7_ns/config_tf_efficientnet_b7_ns_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/tf_efficientnet_b7_ns/config_tf_efficientnet_b7_ns_CosFace_AdamW.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_MagFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_MagFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_MagFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_multi/dpn107/config_dpn107_MagFace_SGD.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/rexnet_200/config_rexnet_200_MagFace_SGD_0.1_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/cspdarknet53/config_cspdarknet53_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 111 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 222 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 333 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_AdamW_0.001_cosine.yaml
python src/fairness_train_timm-vggface2.py --seed 444 --config_path /cmlscratch/sdooley1/merge_timm/FR-NAS/configs_unified_lr/ese_vovnet39b/config_ese_vovnet39b_CosFace_AdamW_0.001_cosine.yaml
