python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_senet154 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_seresnext101_64x4d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetrs200 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xception71 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x3_bitm --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x3_bitm_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large_384_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large_in22k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f1 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f2 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn107 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn131 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnetv2_rw_m --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_320 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_320 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b5 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b5_ns --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_m --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_m_in21ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_m_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_medium_24_p16_224 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_medium_24_p16_224_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name coat_lite_mini --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name coat_lite_tiny --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_small_distilled_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_tiny_distilled_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dla60 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lambda_resnet26t --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_192 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_256 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_384 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_s_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_ti_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_xs_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnest26d --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name rexnet_100 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name visformer_small --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_large_patch32_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_small_r26_s32_224 --input_size 224 --batch_size 250 --seed 222  
