python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ig_resnext101_32x16d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convmixer_1536_20 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_xlarge_384_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_xlarge_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_xlarge_in22k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f3 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f4 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pnasnet5large --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b7 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b7_ap --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b7_ns --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b8 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b8_ap --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_l --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_l_in21ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_l_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_xl_in21ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_xl_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_large_24_p16_224 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_large_24_p16_224_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_large_24_p16_384_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name beit_base_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name beit_base_patch16_224_in22k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name coat_lite_small --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name coat_tiny --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_base_distilled_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_base_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dla102x --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hrnet_w30 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hrnet_w32 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hrnet_w40 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_128 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_128s --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_b_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_b_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resmlp_36_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resmlp_36_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnest50d_4s2x40d --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name rexnet_200 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name skresnext50_32x4d --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name swin_small_patch4_window7_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch16_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch16_224_miil --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch16_224_miil_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch16_sam_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name halo2botnet50ts_256 --input_size 256 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name halonet50ts --input_size 256 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lambda_resnet26rpt_256 --input_size 256 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lamhalobotnet50ts_256 --input_size 256 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name sebotnet33ts_256 --input_size 256 --batch_size 250 --seed 222  
