python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_senet154 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_seresnext101_64x4d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet200d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetrs101 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetrs152 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetrs200 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xception41 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xception65 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xception71 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x3_bitm --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x3_bitm_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_base --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_base_384_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_base_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_base_in22k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large_384_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large_in22ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_large_in22k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_small --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name densenet161 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name densenet201 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f1 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f2 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn107 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn131 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn92 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn98 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name eca_nfnet_l2 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnet101d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b1_pruned --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b3 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b4 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_el --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_es_pruned --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnetv2_rw_m --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnetv2_rw_s --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ens_adv_inception_resnet_v2 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name fbnetc_100 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gernet_l --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hardcorenas_a --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hardcorenas_c --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hardcorenas_d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name inception_v3 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name inception_v4 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lcnet_075 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name legacy_seresnet101 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name legacy_seresnet152 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name legacy_seresnet50 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mixnet_m --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_008 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_040 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_320 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_004 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_006 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_120 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_160 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_320 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetz_d32 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name res2net50_26w_8s --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name res2net50_48w_2s --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name selecsls60b --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name seresnet152d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ssl_resnet50 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name swsl_resnet50 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b2_ns --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b3 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b3_ap --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b4 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b5 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b5_ns --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_cc_b1_8e --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_es --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_lite4 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_m --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_m_in21ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_m_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_s_in21ft1k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_s_in21k --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mixnet_s --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tinynet_d --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tv_resnet101 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tv_resnet152 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name twins_pcpvt_base --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name twins_pcpvt_large --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name wide_resnet101_2 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_medium_24_p16_224 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_medium_24_p16_224_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_small_12_p16_224 --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_small_24_p16_224_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_small_24_p16_384_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_12_p8_224_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_12_p8_384_dist --input_size 112 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name coat_lite_mini --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name coat_lite_tiny --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convit_tiny --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_small_distilled_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_small_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_tiny_distilled_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name deit_tiny_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dla34 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dla46_c --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dla46x_c --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dla60 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hrnet_w18_small --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hrnet_w18_small_v2 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lambda_resnet26t --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_192 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_256 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name levit_384 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_s_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_s_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_ti_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_ti_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name pit_xs_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resmlp_12_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resmlp_12_224_dino --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resmlp_12_distilled_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnest26d --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name rexnet_100 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name skresnet18 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name skresnet34 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name visformer_small --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch32_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch32_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_base_patch32_sam_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_large_patch32_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_small_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_small_patch16_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_small_patch32_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_small_patch32_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_small_r26_s32_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_tiny_patch16_224 --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_tiny_patch16_224_in21k --input_size 224 --batch_size 250 --seed 222  
python3 /cmlscratch/sdooley1/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vit_tiny_r_s16_p8_224_in21k --input_size 224 --batch_size 250 --seed 222  
