python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name adv_inception_v3 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convmixer_1024_20_ks9_p14 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name convnext_tiny --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name cspdarknet53 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name cspresnet50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name cspresnext50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name densenet121 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name densenet169 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name densenetblur121d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dm_nfnet_f0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn68 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name dpn68b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name eca_nfnet_l0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name eca_nfnet_l1 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name eca_resnet33ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name eca_resnext26ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnet101d_pruned --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnet26t --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnet50d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnet50d_pruned --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnet50t --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ecaresnetlight --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b1 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b2_pruned --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_b3_pruned --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_el_pruned --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_em --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_es --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnet_lite0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name efficientnetv2_rw_t --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ese_vovnet19b_dw --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ese_vovnet39b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name fbnetv3_b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name fbnetv3_d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name fbnetv3_g --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gcresnet33ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gcresnet50t --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gcresnext26ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gcresnext50ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gernet_s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ghostnet_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_inception_v3 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet101_v1b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet101_v1c --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet101_v1d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet101_v1s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet18_v1b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet34_v1b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet50_v1b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet50_v1c --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet50_v1d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnet50_v1s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_resnext50_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name gluon_seresnext50_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hardcorenas_b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hardcorenas_e --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name hardcorenas_f --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name inception_resnet_v2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lambda_resnet50ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name lcnet_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name legacy_seresnet34 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name legacy_seresnext50_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mixnet_l --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mixnet_s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mixnet_xl --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mnasnet_small --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv2_050 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv2_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv2_110d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv2_120d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv2_140 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv3_large_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv3_large_100_miil --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv3_large_100_miil_in21k --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name mobilenetv3_rw --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name nf_resnet50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name nfnet_l0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_006 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_016 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_032 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_064 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetx_080 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_002 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_016 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_032 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnety_040 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name regnetz_b16 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name repvgg_a2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name repvgg_b0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name repvgg_b1 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name repvgg_b1g4 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name repvgg_b3 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name res2net50_14w_8s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name res2net50_26w_4s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name res2net50_26w_6s --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name res2next50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet101 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet101d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet18 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet18d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet26 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet26d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet26t --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet32ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet33ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet34 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet34d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet50_gn --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet50d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet51q --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnet61q --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetblur50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetrs50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_101 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_101x1_bitm --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_101x1_bitm_in21k --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x1_bit_distilled --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x1_bitm --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnetv2_50x1_bitm_in21k --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnext50_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name resnext50d_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name selecsls42b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name selecsls60 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name semnasnet_075 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name seresnet33ts --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name seresnext26t_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name spnasnet_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ssl_resnet18 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name ssl_resnext50_32x4d --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name swsl_resnet18 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b0_ap --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b1_ap --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b1_ns --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_b2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_cc_b0_4e --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_cc_b0_8e --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_el --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_em --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_lite0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_lite1 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_lite2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnet_lite3 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_b0 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_b1 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_b2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_efficientnetv2_b3 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_inception_v3 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mixnet_l --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mixnet_m --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mobilenetv3_large_075 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mobilenetv3_large_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mobilenetv3_large_minimal_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mobilenetv3_small_075 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mobilenetv3_small_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tf_mobilenetv3_small_minimal_100 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tinynet_a --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tinynet_b --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tinynet_c --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tv_densenet121 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name tv_resnet34 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name twins_pcpvt_small --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name twins_svt_base --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name twins_svt_small --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vgg11_bn --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vgg13_bn --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vgg16_bn --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name vgg19 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name wide_resnet50_2 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xception --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_nano_12_p16_224 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_nano_12_p16_224_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_nano_12_p16_384_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_nano_12_p8_224 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_nano_12_p8_224_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_nano_12_p8_384_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_small_12_p16_224_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_small_12_p16_384_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_12_p16_224 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_12_p16_224_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_12_p16_384_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_24_p16_224 --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_24_p16_224_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
python3 /cmlscratch/sdooley1/FR-NAS/face.evoLVe.PyTorch/fairness_train_timm.py --backbone_name xcit_tiny_24_p16_384_dist --input_size 112 --batch_size 250 --seed 222   --num_epoch 101
