backbone: gluon_inception_v3
batch_size: 64
bn_eps: null
bn_momentum: null
checkpoints_root: Checkpoints/Phase1B/
clip_grad: null
clip_mode: norm
comet_api_key: D1J58R7hYXPZzqZhrTIOe6GGQ
comet_workspace: samueld
cooldown_epochs: 10
dataset: CelebA
decay_epochs: 100
decay_rate: 0.1
default_test_root: /cmlscratch/sdooley1/data/CelebA/Img/img_align_celeba_splits/test/
default_train_root: /cmlscratch/sdooley1/data/CelebA/Img/img_align_celeba_splits/train/
demographics_file: /cmlscratch/sdooley1/data/CelebA/CelebA_demographics.txt
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
epochs: 100
file_name: timm_from-scratch.csv
file_name_ema: timm_from-scratch_ema.csv
gp: null
groups_to_modify:
- male
- female
head: ArcFace
input_size: 112
layer_decay: null
lr: 0.4
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.5
- 0.5
- 0.5
metadata_file: /cmlscratch/sdooley1/timm_model_metadata.csv
min_lr: 1.0e-06
min_num_images: 3
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
name: CelebA
num_workers: 4
opt: AdamW
opt_betas: null
opt_eps: null
out_dir: .
p_identities:
- 1.0
- 1.0
p_images:
- 1.0
- 1.0
patience_epochs: 10
pretrained: false
project_name: Phase1B
save_freq: 1
sched: cosine
seed: 222
split_bn: false
start_epoch: null
std:
- 0.5
- 0.5
- 0.5
sync_bn: false
torchscript: false
train_loss: Focal
user_config: config_user.yaml
warmup_epochs: 5
warmup_lr: 0.0001
weight_decay: 2.0e-05
