python src/fairness_test_random_timm.py --seed 231 --config_path configs/cait_xs24_384/config_cait_xs24_384_CosFace_adamw.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/coat_lite_small/config_coat_lite_small_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/convit_base/config_convit_base_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/cspdarknet53/config_cspdarknet53_CosFace_adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/dla102x2/config_dla102x2_CosFace_sgd.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/dpn107/config_dpn107_CosFace_sgd.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/ese_vovnet39b/config_ese_vovnet39b_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/fbnetv3_g/config_fbnetv3_g_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/ghostnet_100/config_ghostnet_100_CosFace_sgd.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/gluon_inception_v3/config_gluon_inception_v3_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/gluon_xception65/config_gluon_xception65_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/hrnet_w64/config_hrnet_w64_CosFace_sgd.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/ig_resnext101_32x8d/config_ig_resnext101_32x8d_CosFace_SGD.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/inception_resnet_v2/config_inception_resnet_v2_CosFace_RMSProp.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/inception_v4/config_inception_v4_CosFace_RMSProp.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/jx_nest_base/config_jx_nest_base_CosFace_AdamW.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/legacy_senet154/config_legacy_senet154_CosFace_SGD.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/mobilenetv3_large_100/config_mobilenetv3_large_100_CosFace_RMSpropTF.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/resnetrs101/config_resnetrs101_CosFace_SGD.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/rexnet_200/config_rexnet_200_CosFace_SGD.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/selecsls60b/config_selecsls60b_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/swin_base_patch4_window7_224/config_swin_base_patch4_window7_224_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/tf_efficientnet_b7_ns/config_tf_efficientnet_b7_ns_CosFace_rmsproptf.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/tnt_s_patch16_224/config_tnt_s_patch16_224_CosFace_AdamW.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/twins_svt_large/config_twins_svt_large_CosFace_adamw.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/vgg19/config_vgg19_CosFace_SGD.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/vgg19_bn/config_vgg19_bn_CosFace_SGD.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/visformer_small/config_visformer_small_CosFace_AdamW.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/vit_large_patch16_224/config_vit_large_patch16_224_CosFace_AdamW.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/xception/config_xception_CosFace_Adam.yaml
python src/fairness_test_random_timm.py --seed 231 --config_path configs/xception65/config_xception65_CosFace_Adam.yaml
