T_0: 1000
T_max: 1000000
T_mult: 1
alpha: 0.75
anneal_strategy: cos
backbone: ghostnet_100
base_lr: 0.0001
base_momentum: 0.85
batch_size: 64
betas: !!python/tuple
- 0.9
- 0.999
centered: false
checkpoints_root: Checkpoints/timm_explore_few_epochs/
comet_api_key: KKiKMVZI9RCYowoKDZDS5Y2km
comet_workspace: rsukthanker
cooldown: 0
cycle_momentum: true
dampening: 0
dataset: CelebA
default_test_root: /work/dlclarge2/sukthank-ZCP_Competition/FairNAS/FR-NAS/data/CelebA/Img/img_align_celeba_splits/test/
default_train_root: /work/dlclarge2/sukthank-ZCP_Competition/FairNAS/FR-NAS/data/CelebA/Img/img_align_celeba_splits/train/
demographics_file: CelebA/CelebA_demographics.txt
div_factor: 25.0
dropout: 0.3
end_factor: 1.0
epochs: null
eps: 1.0e-08
eta_min: 0.0
etas: !!python/tuple
- 0.5
- 1.2
factor: 0.3333333333333333
file_name: timm_from-scratch.csv
final_div_factor: 10000.0
gamma: 0.1
groups_to_modify:
- male
- female
head: CosFace
history_size: 100
initial_accumulator_value: 0
input_size: 112
lambd: 0.0001
last_epoch: -1
line_search_fn: null
lr: 0.001
lr_decay: 0
lr_lambda:
- 0.01
- 0.02
max_eval: null
max_iter: 20
max_lr: 3
max_momentum: 0.95
mean:
- 0.5
- 0.5
- 0.5
metadata_file: timm_model_metadata.csv
milestones:
- 30
- 80
min_lr: 0.0
min_num_images: 3
mode: min
momentum: 0.9
momentum_decay: 0.004
name: CelebA
num_epoch: 100
num_workers: 4
optimizer: SGD
out_dir: .
p_identities:
- 1.0
- 1.0
p_images:
- 1.0
- 1.0
patience: 10
pct_start: 0.3
pretrained: false
project_name: from-scratch_no-resampling_adam
rho: 0.9
scale_mode: cycle
scheduler: CosineAnnealingLR
seed: 222
start_factor: 0.3333333333333333
std:
- 0.5
- 0.5
- 0.5
step_size: 30
step_size_down: null
step_size_up: 2000
step_sizes: !!python/tuple
- 1.0e-06
- 50
steps_per_epoch: 1000
t0: 1000000.0
three_phase: false
threshold: 0.0001
threshold_mode: rel
tolerance_change: 1.0e-09
tolerance_grad: 1.0e-07
total_iters: 5
total_steps: null
train_loss: Focal
user_config: config_user.yaml
verbose: false
weight_decay: 0
