python src/fairness_test_timm.py --config_path configs_multi/inception_v4/config_inception_v4_CosFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/legacy_senet154/config_legacy_senet154_ArcFace_SGD.yaml
python src/fairness_test_timm.py --config_path configs_multi/rexnet_200/config_rexnet_200_CosFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/selecsls60b/config_selecsls60b_MagFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/tnt_s_patch16_224/config_tnt_s_patch16_224_ArcFace_SGD.yaml
python src/fairness_test_timm.py --config_path configs_multi/vgg19/config_vgg19_ArcFace_SGD.yaml
python src/fairness_test_timm.py --config_path configs_multi/vgg19/config_vgg19_ArcFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/vgg19_bn/config_vgg19_bn_ArcFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/vgg19_bn/config_vgg19_bn_ArcFace_SGD.yaml
python src/fairness_test_timm.py --config_path configs_multi/visformer_small/config_visformer_small_ArcFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/visformer_small/config_visformer_small_ArcFace_SGD.yaml
python src/fairness_test_timm.py --config_path configs_multi/xception/config_xception_ArcFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/xception/config_xception_ArcFace_SGD.yaml
python src/fairness_test_timm.py --config_path configs_multi/xception65/config_xception65_ArcFace_AdamW.yaml
python src/fairness_test_timm.py --config_path configs_multi/xception65/config_xception65_ArcFace_SGD.yaml
