#python src/fix_disk_error.py --config_path configs/gluon_xception65/config_gluon_xception65_CosFace_Adam.yaml
#python src/fix_disk_error.py --config_path configs/ig_resnext101_32x8d/config_ig_resnext101_32x8d_CosFace_SGD.yaml
#python src/fix_disk_error.py --config_path configs/inception_resnet_v2/config_inception_resnet_v2_CosFace_RMSProp.yaml
#python src/fix_disk_error.py --config_path configs/inception_v4/config_inception_v4_CosFace_RMSProp.yaml
#python src/fix_disk_error.py --config_path configs/legacy_senet154/config_legacy_senet154_CosFace_SGD.yaml
python src/fix_disk_error.py --config_path configs/mobilenetv3_large_100/config_mobilenetv3_large_100_CosFace_RMSpropTF.yaml
python src/fix_disk_error.py --config_path configs/resnetrs101/config_resnetrs101_CosFace_SGD.yaml
python src/fix_disk_error.py --config_path configs/rexnet_200/config_rexnet_200_CosFace_SGD.yaml
#python src/fix_disk_error.py --config_path configs/selecsls60b/config_selecsls60b_CosFace_Adam.yaml